# NoBlockCreeper Plugin Configuration
visualEffect: true  # Set to false to disable the visual explosion effect
explosionPower: 4.0  # The power of the explosion (0.0 to 100.0, adjust as needed)
preventCreeperExplosions: true  # Set to true to prevent creeper explosions
