name: NoBlockCreeperPlugin
version: '2.0'
main: net.abhinav.nbc.NoBlockCreeper
api-version: '1.21'
load: STARTUP
authors: [ Abhinav VS ]
commands:
  togglecreepergrief:
    description: Toggle Creeper grief prevention on/off.
    usage: /togglecreepergrief
    permission: noblockcreeper.toggle
    permission-message: You do not have permission to toggle Creeper grief prevention.
permissions:
  noblockcreeper.toggle:
    description: Allows players to toggle Creeper grief prevention.
    default: op